export const actionTypes = {
    //- fetching 2021 history data
    FETCHING_HISTORY_DATA_21: 'FETCHING_HISTORY_DATA_21',
    FETCHING_HISTORY_DATA_21_SUCCESS: 'FETCHING_HISTORY_DATA_21_SUCCESS',
    FETCHING_HISTORY_DATA_21_FAIL: 'FETCHING_HISTORY_DATA_21_FAIL',
    //- fetching global history data
    FETCHING_HISTORY_DATA_ALL: 'FETCHING_HISTORY_DATA_ALL',
    FETCHING_HISTORY_DATA_ALL_SUCCESS: 'FETCHING_HISTORY_DATA_ALL_SUCCESS',
    FETCHING_HISTORY_DATA_ALL_FAIL: 'FETCHING_HISTORY_DATA_ALL_FAIL',
    //-Global data Today
    FETCHING_TODAY_GLOBAL_DATA: 'FETCHING_TODAY_GLOBAL_DATA',
    FETCHING_TODAY_GLOBAL_DATA_SUCCESS: 'FETCHING_TODAY_GLOBAL_DATA_SUCCESS',
    FETCHING_TODAY_GLOBAL_DATA_FAIL: 'FETCHING_TODAY_GLOBAL_DATA_FAIL',
    //-Global data Yesterday
    FETCHING_YESTERDAY_GLOBAL_DATA: 'FETCHING_YESTERDAY_GLOBAL_DATA',
    FETCHING_YESTERDAY_GLOBAL_DATA_SUCCESS: 'FETCHING_YESTERDAY_GLOBAL_DATA_SUCCESS',
    FETCHING_YESTERDAY_GLOBAL_DATA_FAIL: 'FETCHING_YESTERDAY_GLOBAL_DATA_FAIL',
    //- Vaccine
    FETCHING_VACCINE_DATA: 'FETCHING_VACCINE_DATA',
    FETCHING_VACCINE_DATA_SUCCESS: 'FETCHING_VACCINE_DATA_SUCCESS',
    FETCHING_VACCINE_DATA_FAIL: 'FETCHING_VACCINE_DATA_FAIL',
    //-CountriesData
    FETCHING_COUNTRIES_DATA: 'FETCHING_COUNTRIES_DATA',
    FETCHING_COUNTRIES_DATA_SUCCESS: 'FETCHING_COUNTRIES_DATA_SUCCESS',
    FETCHING_COUNTRIES_DATA_FAIL: 'FETCHING_COUNTRIES_DATA_FAIL',
};
